management:
  context-path: /admin

server:
  port: 8080

product:
  version: 1.1
gateway:
  version: 1.0

filter:
  sanitize:
    url: /api/v1/filter/sanitize
guestbook:
  messages:
    url: /api/v1/guestbook/messages